Repository niegfg/amazon-clone, pull requests merged in 2022-10, with the labels that each got.

#15 Add hover effect on Images #9
  css/style.css
  index.html
Labels: hacktoberfest

#24 Issue #23: Update with "Back to Top" feature
  css/style.css
  index.html
Labels: hacktoberfest

#26 Update index.html
  index.html
Labels: hacktoberfest

#6 Update index.html
  index.html
Labels: good first issue, hacktoberfest

#33 Reduced the hovering scale of the images
  css/style.css
Labels: good first issue, hacktoberfest

#37 Redirected the logo in the product page to the the home page
  product.html
Labels: hacktoberfest

#58 Added the Footer section in the product page
  css/product.css
  product.html
Labels: hacktoberfest-accepted

#63 fixed padding in navbar
  css/style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#65 fixed the responsivesness, padding and position in product.html
  css/product.css
  index.html
  product.html
Labels: bug, good first issue, hacktoberfest, hacktoberfest-accepted

#32 Adding login Page
  Login.css
  index.html
  login.html
  loginjs.js
Labels: hacktoberfest, hacktoberfest-accepted

#45 Made Cart Button functional added billing.html
  billing.html
  css/billing.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#52 pointer on hovering 'buy now' and 'add to cart' button
  css/product.css
  css/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#61 added a carousel in hero section
  css/style.css
  img/carousel-section/beauty.jpg
  img/carousel-section/hero.jpg
  img/carousel-section/sofa.jpg
  img/carousel-section/toys.jpg
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#68 changes made in navbar
  css/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#70 Issue #59 resolved:thickness of scrollbar fixed
  css/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#71 login page link added to all sign in options
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#72 center aligned log in button
  Login.css
Labels: hacktoberfest, hacktoberfest-accepted
